GET http://localhost:8080/cats

###

POST http://localhost:8080/cats
Content-Type: application/json

{
    "name": "Sigge",
    "age": 3,
    "favoriteFood": "Cheese",
    "id": 3
}

### 
PUT http://localhost:8080/cats

### 
DELETE  http://localhost:8080/cats