GET http://localhost:8080/api/cats

###

GET http://localhost:8080/api/cats/1

###

POST http://localhost:8080/api/cats
Content-Type: application/json

{
    "name": "Sigge",
    "age": 3,
    "favoriteFood": "Cheese",
    "id": 3
}

### 
PUT http://localhost:8080/api/cats/1
Content-Type: application/json

{
    "name": "Sigge",
    "age": 3,
    "favoriteFood": "Cheese",
    "id": 1
}


### 
DELETE  http://localhost:8080/api/cats/id