GET http://localhost:8080/users

###

POST http://localhost:8080/users
Content-Type: application/json

{
    "name": "Pelle",
    "age": 55,
    "id": 3
}

### 
PUT http://localhost:8080/users

### 
DELETE  http://localhost:8080/users